version: '3.8'

services:

  app:
      build: .
      image: authentication-api:latest
      ports:
        - '3000:3000'
      environment:
        DATABASE_URL: "postgresql://postgres:postgres@db:5432/authentication?schema=public"
      depends_on:
        - database

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
